service: action-tesla-at-home

provider:
    name: aws
    runtime: nodejs12.x
    stage: dev
    region: eu-north-1

plugins:
    - serverless-dotenv-plugin

functions:
    app:
        handler: lib/handler.app
        events:
            - http:
                path: /{proxy+}
                method: GET
                cors: true
            - http:
                path: /{proxy+}
                method: POST
                cors: true
    